[package]
name = "datimeline"
version = "0.1.0"
authors = ["abertrand"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nalgebra = "0.18.0"
num-traits = "0.2"
alga = "0.9.1"